//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstagioEntities : DbContext
    {
        public EstagioEntities()
            : base("name=EstagioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_alunos> tb_alunos { get; set; }
        public virtual DbSet<tb_candidato> tb_candidato { get; set; }
        public virtual DbSet<tb_empresas> tb_empresas { get; set; }
        public virtual DbSet<tb_vagas> tb_vagas { get; set; }
        public virtual DbSet<vw_candidato> vw_candidato { get; set; }
        public virtual DbSet<vw_vagas> vw_vagas { get; set; }
    }
}
