//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_alunos
    {
        public int id_aluno { get; set; }
        public string nm_aluno { get; set; }
        public string nm_curso { get; set; }
        public string ds_anoEstudo { get; set; }
        public System.DateTime dt_nascimento { get; set; }
        public int ds_idade { get; set; }
        public string ds_endereco { get; set; }
        public int ds_numero { get; set; }
        public string ds_bairro { get; set; }
        public string ds_cep { get; set; }
        public string nr_fixo { get; set; }
        public string nr_celular { get; set; }
        public string ds_seEstuda { get; set; }
        public string ds_qualCurso { get; set; }
        public string ds_turno { get; set; }
        public string ds_expProfissional { get; set; }
        public string ds_areaPreferencia { get; set; }
    }
}
